# Generated by Django 4.2.7 on 2024-01-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_libraryinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminUserName', models.CharField(max_length=150)),
                ('adminUserCountry', models.CharField(max_length=150)),
                ('adminUsernumber', models.CharField(max_length=150)),
                ('adminPassword', models.CharField(max_length=150)),
                ('adminConfirmPassword', models.CharField(max_length=150)),
                ('adminGender', models.CharField(max_length=150)),
                ('adminEmail', models.CharField(max_length=150)),
            ],
        ),
    ]
