# Generated by Django 4.2.7 on 2024-01-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='adminStatus',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
