# Generated by Django 4.2.7 on 2024-01-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_alter_adminuser_adminstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='tenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenantUserProfile', models.ImageField(upload_to='Profile/')),
                ('tenantUserName', models.CharField(max_length=150)),
                ('tenantUserCountry', models.CharField(max_length=150)),
                ('tenantPassword', models.CharField(max_length=150)),
                ('tenantConfirmPassword', models.CharField(max_length=150)),
                ('tenantGender', models.CharField(max_length=150)),
                ('tenantUsernumber', models.CharField(max_length=150)),
                ('tenantUseremail', models.CharField(max_length=150)),
                ('tenantadminUserAddress', models.CharField(max_length=150)),
                ('tenantDocumentProof', models.ImageField(upload_to='document/')),
                ('monthRentDate', models.DateField()),
                ('price', models.CharField(max_length=150)),
                ('agreementStartDate', models.DateField()),
                ('agreementEndDate', models.DateField()),
                ('estatePic1', models.ImageField(upload_to='estatePic1/')),
                ('estatePic2', models.ImageField(upload_to='estatePic2/')),
                ('estatePic3', models.ImageField(upload_to='estatePic3/')),
                ('estatePic4', models.ImageField(upload_to='estatePic4/')),
                ('rentalType', models.CharField(max_length=150)),
                ('adminStatus', models.CharField(default='Active', max_length=150)),
                ('gymFacility', models.CharField(max_length=150)),
                ('foodService', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='adminStatus',
            field=models.CharField(default='Active', max_length=150),
        ),
    ]
