# Generated by Django 4.2.7 on 2024-01-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_tenantuser_alter_adminuser_adminstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='estatePic1',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='estatePic2',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='estatePic3',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='estatePic4',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='tenantUserProfile',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
