# Generated by Django 4.2.7 on 2024-01-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_alter_tenantuser_estatepic1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='estatePic1',
            field=models.ImageField(blank=True, default='image/no_image.jpg', null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='estatePic2',
            field=models.ImageField(blank=True, default='image/no_image.jpg', null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='estatePic3',
            field=models.ImageField(blank=True, default='image/no_image.jpg', null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='estatePic4',
            field=models.ImageField(blank=True, default='image/no_image.jpg', null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='tenantUserProfile',
            field=models.ImageField(blank=True, default='image/default-profile-account-unknown-icon-black-silhouette-free-vector.jpg', null=True, upload_to='image/'),
        ),
    ]
