# Generated by Django 4.2.7 on 2024-01-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_alter_tenantuser_estatepic1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='tenantDocumentProof',
            field=models.ImageField(blank=True, default='image/no_image.jpg', null=True, upload_to='image/'),
        ),
    ]
